//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.15 at 11:07:56 PM EET 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sorgu_id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="merkez_no" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="sube_no" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="gise_no" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="sicil_no" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="islem_kanali" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="islem_tipi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="islem_adi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="tinnumberdata" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="namedata" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="countrydata" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="birthdate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sorguId",
    "merkezNo",
    "subeNo",
    "giseNo",
    "sicilNo",
    "islemKanali",
    "islemTipi",
    "islemAdi",
    "tinnumberdata",
    "namedata",
    "countrydata",
    "birthdate"
})
@XmlRootElement(name = "getPersonRequest")
public class GetPersonRequest {

    @XmlElement(name = "sorgu_id")
    protected int sorguId;
    @XmlElement(name = "merkez_no")
    protected int merkezNo;
    @XmlElement(name = "sube_no")
    protected int subeNo;
    @XmlElement(name = "gise_no")
    protected int giseNo;
    @XmlElement(name = "sicil_no")
    protected int sicilNo;
    @XmlElement(name = "islem_kanali", required = true)
    protected String islemKanali;
    @XmlElement(name = "islem_tipi", required = true)
    protected String islemTipi;
    @XmlElement(name = "islem_adi", required = true)
    protected String islemAdi;
    protected String tinnumberdata;
    protected String namedata;
    protected String countrydata;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthdate;

    /**
     * Gets the value of the sorguId property.
     * 
     */
    public int getSorguId() {
        return sorguId;
    }

    /**
     * Sets the value of the sorguId property.
     * 
     */
    public void setSorguId(int value) {
        this.sorguId = value;
    }

    /**
     * Gets the value of the merkezNo property.
     * 
     */
    public int getMerkezNo() {
        return merkezNo;
    }

    /**
     * Sets the value of the merkezNo property.
     * 
     */
    public void setMerkezNo(int value) {
        this.merkezNo = value;
    }

    /**
     * Gets the value of the subeNo property.
     * 
     */
    public int getSubeNo() {
        return subeNo;
    }

    /**
     * Sets the value of the subeNo property.
     * 
     */
    public void setSubeNo(int value) {
        this.subeNo = value;
    }

    /**
     * Gets the value of the giseNo property.
     * 
     */
    public int getGiseNo() {
        return giseNo;
    }

    /**
     * Sets the value of the giseNo property.
     * 
     */
    public void setGiseNo(int value) {
        this.giseNo = value;
    }

    /**
     * Gets the value of the sicilNo property.
     * 
     */
    public int getSicilNo() {
        return sicilNo;
    }

    /**
     * Sets the value of the sicilNo property.
     * 
     */
    public void setSicilNo(int value) {
        this.sicilNo = value;
    }

    /**
     * Gets the value of the islemKanali property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIslemKanali() {
        return islemKanali;
    }

    /**
     * Sets the value of the islemKanali property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIslemKanali(String value) {
        this.islemKanali = value;
    }

    /**
     * Gets the value of the islemTipi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIslemTipi() {
        return islemTipi;
    }

    /**
     * Sets the value of the islemTipi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIslemTipi(String value) {
        this.islemTipi = value;
    }

    /**
     * Gets the value of the islemAdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIslemAdi() {
        return islemAdi;
    }

    /**
     * Sets the value of the islemAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIslemAdi(String value) {
        this.islemAdi = value;
    }

    /**
     * Gets the value of the tinnumberdata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTinnumberdata() {
        return tinnumberdata;
    }

    /**
     * Sets the value of the tinnumberdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTinnumberdata(String value) {
        this.tinnumberdata = value;
    }

    /**
     * Gets the value of the namedata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamedata() {
        return namedata;
    }

    /**
     * Sets the value of the namedata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamedata(String value) {
        this.namedata = value;
    }

    /**
     * Gets the value of the countrydata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountrydata() {
        return countrydata;
    }

    /**
     * Sets the value of the countrydata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountrydata(String value) {
        this.countrydata = value;
    }

    /**
     * Gets the value of the birthdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthdate() {
        return birthdate;
    }

    /**
     * Sets the value of the birthdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthdate(XMLGregorianCalendar value) {
        this.birthdate = value;
    }

}
