//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.05 at 04:49:42 PM EET 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="searchuser" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="searchdepartment" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="searchlocation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="searchapplication" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="tinnumberdata" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="namedata" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="countrydata" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="birthdate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "searchuser",
    "searchdepartment",
    "searchlocation",
    "searchapplication",
    "tinnumberdata",
    "namedata",
    "countrydata",
    "birthdate"
})
@XmlRootElement(name = "getPersonRequest")
public class GetPersonRequest {

    @XmlElement(required = true)
    protected String searchuser;
    @XmlElement(required = true)
    protected String searchdepartment;
    @XmlElement(required = true)
    protected String searchlocation;
    @XmlElement(required = true)
    protected String searchapplication;
    protected String tinnumberdata;
    protected String namedata;
    protected String countrydata;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthdate;

    /**
     * Gets the value of the searchuser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchuser() {
        return searchuser;
    }

    /**
     * Sets the value of the searchuser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchuser(String value) {
        this.searchuser = value;
    }

    /**
     * Gets the value of the searchdepartment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchdepartment() {
        return searchdepartment;
    }

    /**
     * Sets the value of the searchdepartment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchdepartment(String value) {
        this.searchdepartment = value;
    }

    /**
     * Gets the value of the searchlocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchlocation() {
        return searchlocation;
    }

    /**
     * Sets the value of the searchlocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchlocation(String value) {
        this.searchlocation = value;
    }

    /**
     * Gets the value of the searchapplication property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchapplication() {
        return searchapplication;
    }

    /**
     * Sets the value of the searchapplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchapplication(String value) {
        this.searchapplication = value;
    }

    /**
     * Gets the value of the tinnumberdata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTinnumberdata() {
        return tinnumberdata;
    }

    /**
     * Sets the value of the tinnumberdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTinnumberdata(String value) {
        this.tinnumberdata = value;
    }

    /**
     * Gets the value of the namedata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamedata() {
        return namedata;
    }

    /**
     * Sets the value of the namedata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamedata(String value) {
        this.namedata = value;
    }

    /**
     * Gets the value of the countrydata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountrydata() {
        return countrydata;
    }

    /**
     * Sets the value of the countrydata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountrydata(String value) {
        this.countrydata = value;
    }

    /**
     * Gets the value of the birthdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthdate() {
        return birthdate;
    }

    /**
     * Sets the value of the birthdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthdate(XMLGregorianCalendar value) {
        this.birthdate = value;
    }

}
