//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 11:58:12 AM EET 
//


package io.spring.guides.gs_producing_web_service;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WLmwldataMatchResultXML complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WLmwldataMatchResultXML"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="matchScore" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="matchStatus" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="matchMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="matchResult" type="{http://spring.io/guides/gs-producing-web-service}WlmwldataFindXML" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WLmwldataMatchResultXML", propOrder = {
    "matchScore",
    "matchStatus",
    "matchMessage",
    "matchResult"
})
public class WLmwldataMatchResultXML {

    protected Integer matchScore;
    protected Boolean matchStatus;
    protected String matchMessage;
    protected List<WlmwldataFindXML> matchResult;

    /**
     * Gets the value of the matchScore property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMatchScore() {
        return matchScore;
    }

    /**
     * Sets the value of the matchScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMatchScore(Integer value) {
        this.matchScore = value;
    }

    /**
     * Gets the value of the matchStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMatchStatus() {
        return matchStatus;
    }

    /**
     * Sets the value of the matchStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMatchStatus(Boolean value) {
        this.matchStatus = value;
    }

    /**
     * Gets the value of the matchMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatchMessage() {
        return matchMessage;
    }

    /**
     * Sets the value of the matchMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatchMessage(String value) {
        this.matchMessage = value;
    }

    /**
     * Gets the value of the matchResult property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the matchResult property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMatchResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WlmwldataFindXML }
     * 
     * 
     */
    public List<WlmwldataFindXML> getMatchResult() {
        if (matchResult == null) {
            matchResult = new ArrayList<WlmwldataFindXML>();
        }
        return this.matchResult;
    }

}
